### ISSUE TITLE
Multi-device editing/syncing with CRDTs

### ISSUE THREAD

**Issue by trishume** [google/xi-editor#250]
This is a tracking issue/roadmap/plan for how I'm going to proceed with adding the ability to synchronize documents. The tasks below correspond approximately to PRs I plan on writing and the order I plan on doing them.

cc @raphlinus 

## Stage 1 - `xi-rope`

- [ ] Implement Serde serialize/deserialize for `Revision`, possibly `Engine` and transitive dependencies.
    - [ ] Read code and figure out what exactly the state needing synchronization is. Is it just a `Vec<Revision>`, I think I may also need a `Rope` like `Engine` but I haven't read `engine.rs` yet so I don't quite know how things fit together.
    - [ ] If I need a `Rope`, might need a custom serializer to make it serialize as a string or something, serializing the tree structure like a derive would do seems unnecessary.
- [ ] Add option to disable garbage collection. This is needed to allow unbounded time between synchronization.
- [ ] Implement a "merge" operation that takes two states (`Revision` histories?) and produces a new state that incorporates the changes from both.
- [ ] Write tests for this merge operation. Possibly including [quickcheck](https://github.com/BurntSushi/quickcheck) tests or fuzz tests.

## Stage 2 - Fuchsia

As an initial use case of this functionality, implement syncing using [ledger](https://fuchsia.googlesource.com/ledger/) for [fuchsia/xi](https://fuchsia.googlesource.com/xi).

- [ ] Create a new crate in `xi-editor` for ledger document syncing hidden behind a Cargo feature. (or maybe this can just be a Cargo feature on `xi-rope`?)
- [ ] Hook up a Rust binding for the `fidl` interface for ledger.
- [ ] Use the previously built serialization and merge functions to implement syncing using ledger.
- [ ] Add a test command that opens a synchronized document for demo purposes at a standard location so it can be edited from multiple Fuchsia instances.

## Stage 3 - Make it fast

The above will have terrible awful scaling properties and will slow to a crawl in many use cases. The next step is to figure out ways to improve the CRDT representation and operations to have better time and space complexity. Possibly using techniques from [this prototype](https://github.com/google/ot-crdt-papers) and maybe some new ones if I think of any. Preliminary plan:

- [ ] Write down scaling problems of existing solution
- [ ] [Think real hard](http://wiki.c2.com/?FeynmanAlgorithm)
- [ ] Write down the solution

**Comment by trishume** [comment]
I discussed this a bunch with @raphlinus today and now have a much better understanding of the whole CRDT model and how to proceed. I've included some (very high-res page-bloaty) pictures of the whiteboard from our discussion along with some quick notes. I've edited the main issue body based on the discussion with new items.

cc @cmyr @rkusa since both of you expressed interest in CRDT stuff

Example of a revision history, right column is the deletion set at every revision, identical concurrent deletions (last two) necessitate multi-set (each deleted index also has a count) for reversibility so that undoing/reversing one doesn't un-delete a multi-deleted character. Things along the bottom are state in the engine for the head revision:
![img_20170504_140057](https://cloud.githubusercontent.com/assets/887610/25733403/83c64dc8-310d-11e7-96ed-2c8b517b455b.jpg)
top right is the contents of a revision currently:
![img_20170504_140104](https://cloud.githubusercontent.com/assets/887610/25733404/83cc31ac-310d-11e7-8146-54a815214890.jpg)
example of a non-trivial merge (bot-left) and half of a diagram showing correspondence between ops (which include the inserted or deleted string) and revs (which only include index sets and rely on text and tombstone ropes stored in the engine for the head revision):
![img_20170504_151728](https://cloud.githubusercontent.com/assets/887610/25733400/83c4437a-310d-11e7-99c4-29b21010196e.jpg)
other half of diagram, plus drawings of how one might efficiently represent histories and ropes as key-values so that only a limited amount of keys/data are changed on update:
![img_20170504_151721](https://cloud.githubusercontent.com/assets/887610/25733402/83c63716-310d-11e7-9d4a-c44af9c33e34.jpg)
example of correspondence between deletion set and function from index to element, with set of non-primes corresponding to function of nth prime:
![img_20170504_140124](https://cloud.githubusercontent.com/assets/887610/25733401/83c4eda2-310d-11e7-87ce-2c7729491cae.jpg)

**Comment by rkusa** [comment]
Thanks for the update!

I have a question to the first image. Why is the deletion set at line three (`ab ins={1} {1}`) `{1}` and not `{2}`?

Another question regarding the tombstones. Since they are not part of the revision, we only have the most reason tomstone string, right?

I've added the tombstone state to each line of your first example (and also added an additional starting line for the sake of my following question).

```
(1) 123   del={0, 1, 2}   {0, 1, 2}
      text = "" tombstones = "123"
(2) a     ins={0}         {1, 2}
      text = "a" tombstones = "23"
(3) ab    ins={1}         {1}
      text = "ab" tombstones = "3"
(4) axb   ins={1}         {}
      text = "axb" tombstones = ""
(5) ab    del={1}         {1}
      text = "ab" tombstones = "x"
```

Is this the correct way of how tombstones are going to work? If yes, when I undo all of these revision (`(5)`, `(4)`, `(3)`, `(2)` and `(1)`), how do we know that we have to restore `123` (because `123` it is not in the tombstone string anymore)?

**Comment by trishume** [comment]
The leftmost deletion set, also known as `from_union` or the interleaving, is the characters deleted to get the final string. To be clear in the whiteboard diagram, the rightmost column is things that can be computed at the current time after all the revisions based on information at the bottom rather than stuff stored in a revision or computed at that time. So since the union string at the bottom is "axb", the deletion set to get "ab" is `{1}`.

Let me rewrite your example to be correct. Below the first line is in the revision, and the next line is the contents of `Engine` just after that revision is made. I included both the `text,tombstones` representation and the `union` representation, but in reality only one would be included. For the `union`, `from_union` is just the characters to delete to get `text`, and for `text,tombstones` you can get the union by using `from_union` to determine an interleaving. You also need `from_union` to figure out indexes to put in revisions since the indexes are based on the union string. The `text,tombstones` representation is an optimization of `union` that is more complex but also more efficient. I also included `back_computed_deletions_from_6_union` which is not something known at each time but something that can be computed at the very end, possibly for undo processing or something, it corresponds to the leftmost column of the drawing, I don't know if it is actually useful, it's just something we talked about to make sure I was understanding it right.
```
()   before any revisions are made
      text = "" tombstones = "" union="" from_union={}
      back_computed_deletions_from_6_union = {0,1,2,3,4,5}
(1) ins={0, 1, 2}
      text = "123" tombstones = "" union="123" from_union={}
      back_computed_deletions_from_6_union = {0,1,2}
(2)  del={0, 1, 2}
      text = "" tombstones = "123" union="123" from_union={0,1,2}
      back_computed_deletions_from_6_union = {0,1,2,3,4,5}
(3) ins={0}
      text = "a" tombstones = "123" union="a123" from_union={1,2,3}
      back_computed_deletions_from_6_union = {1,2,3,4,5}
(4) ins={1}
      text = "ab" tombstones = "123" union="ab123" from_union={2,3,4}
      back_computed_deletions_from_6_union = {1,3,4,5}
(5) ins={1}
      text = "axb" tombstones = "123" union="axb123" from_union={3,4,5}
      back_computed_deletions_from_6_union = {3,4,5}
(6) del={1}
      text = "ab" tombstones = "x123" union="axb123" from_union={1,3,4,5}
```

**Comment by rkusa** [comment]
Now, it makes sense. Thanks a lot for the detailed answer!

**Comment by cmyr** [comment]
@erlend-sh These two projects aren't particularly related, so I don't think it makes too much sense to think of compatibility; however my understanding is that Memo is designed to be a standalone system that exposes an API that can be used by any consumer, so supporting it in xi at some point in the future should definitely be possibly. It's certainly an interesting project, and I've been following along with interest. :)

**Comment by ul** [comment]
Is there any ongoing work for this project? I'm especially interested in "Support Undo operations in the CRDT". Is anyone having a deep Engine understanding keen to work on it with me? I also could offer a bounty for this implementation.
