### ISSUE TITLE
May 2017 Roadmap

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#252]
This is a basic roadmap for xi editor. It does not represent a commitment, or a strict ordering of when features will be done, but does outline the current thinking. As a community-driven project, contributors should feel free to pick up a desired feature and make it happen.

While development is ongoing, the MacOS/Cocoa front end (at [xi-mac](https://github.com/google/xi-mac)) is considered the "reference implementation". Contributors are welcome (and encouraged) to play around with other frontends, but various aspects of the RPC protocol are going to be in flux for the forseeable future. The Fuchsia front end (at [fuchsia/xi](https://fuchsia.googlesource.com/xi)) is also officially maintained, but only has a subset of the capabilities.

### next/alpha/towards a useable editor (summer 2017?)
The immediate goal is to get xi to a point where it is a suitable choice for basic text editing, and to enable development of basic plugins.

- [ ] automatic linewrap (#184)
- [ ] horizontal scrolling (https://github.com/google/xi-mac/issues/4)
- simple find/replace (https://github.com/google/xi-mac/issues/9, #150 #224)
  - [x] find (#286, https://github.com/google/xi-mac/pull/47)
  - [ ] replace
- [x] automatic syntax highlighting (inc. automatic syntax detection) (this comes down to improved plugin support) (closed #285)
- [ ] auto-indentation (ditto)
- [x] warn on close with unsaved changes (closed #174)
- [ ] preliminary plugin support (discussion #189, tracking #253)
- [x] Goto-line ? (#190) (closed #192)
- [x] multiple cursors (#188)

### near future
Things that are definitely planned

- [ ] stabilization and good documentation of front-end protocol
- [x] multi device editing (may be Fuchsia-only at first) (tracking #250)
- [x] making the syntect plugin properly incremental (#401)
- [ ] multiple views into a single buffer
- [ ] split windows (#170)
- [ ] remapping keys
- [x] more customization, generally (#410)
- [ ] full plugin support (inc. language server protocol)
- [ ] better i18n and Unicode support (including bidi)
- [x] better testing (improved, but lots more to do)
- [ ] profiling and profile visualization

### future
(one day)

- [ ] modal editing (vi mode) (#93)
- [ ] rich text (similar document model as Markdown)
- [ ] some form of workspace, or navigation through multiple files (#181)
- [ ] xi-lang (improved syntax highlighting & language support)

### deep future
(who knows)

- [ ] collaborative editing
- [ ] remote sessions
- [ ] [crispr integration](https://xkcd.com/1823/)

-----
New roadmap as of November 2017: #437

**Comment by cmyr** [comment]
This is superseded by #437.
