### ISSUE TITLE
Reworked plugin edits tracking issue

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#466]
For a while we've been talking about a few changes to how plugin edits are handled; this has been brought up again because it is interfering with our ability to implement things like autoindent.

There are a number of distinct changes around plugin edits, which it makes sense to tackle en masse:

- [x] finger grained edits / delta edits: we currently have a unique representation for plugin edits, when it makes more sense to have plugins use the same Delta representation we use elsewhere in `xi-core`.  This entails implementing serialize/deserialize for deltas, and updating the plugin libraries appropriately.
- [x] send line numbers with updates: (#496) this also means updating plugin libraries to track and update these line offsets, and use them to transparently fetch lines as needed.
- [x] async plugin edits (#367); more specifically, we want to deprecate the current synchronous API for plugin edits, and make this async only.

Currently unclear to me: whether deltas can currently represent cursor priority; and what this means for undo gc, specifically around tracking 'oldest active revision'.

**Comment by cmyr** [comment]
@betterclever This could be a good issue for you to close out.

Take a look at #367. This PR adds the ability for plugins to send edits asynchronously; plugins can send a notification to core with an edit. Previously the plugin could only make an edit in response to an update sent from core.

We would like to remove the old behaviour. When a plugin gets an update, it has to send an acknowledgement, but it does not send an actual edit; any edits would be sent as notifications, using the new API.

This would involve some changes in core, and it would also involve updating syntect to the new behaviour. There will be some tricky bits, but I think it will give you a good idea of the overall plugin system.
