### ISSUE TITLE
[GSoC] Find enhancements

### ISSUE THREAD

**Issue by scholtzan** [google/xi-editor#634]
This is a basic roadmap of the steps I am planning to take to provide more advanced search and replace functionality in xi editor. I will integrate a more advanced interface for find and replace into xi mac (https://github.com/google/xi-mac/issues/174). 

## Roadmap

_I am planning to refine this roadmap over time._

- [x] Plan architecture of search and replace functionality for xi editor
- [x] Outsource find logic from `view.rs` into separate file
- [x] Plan RPC for search (https://github.com/google/xi-editor/issues/664)
- [x] Search Query stored in core
- [x] Notification for number of search results from core to front-end
- [x] Use selection for find (<kbd>CMD</kbd> + <kbd>E</kbd>) (https://github.com/google/xi-editor/pull/701)
- [x] Whole words find option (used for <kbd>CMD</kbd> + <kbd>D</kbd>) (https://github.com/google/xi-editor/pull/711)
- [x] Find all (https://github.com/google/xi-editor/pull/720)
- [x] Fixing of bugs
    - [x] Fix find creating unexpected selections (https://github.com/google/xi-editor/issues/346)
- [x] Search using regular expressions in xi editor
    - [ ] Regex search avoid the copy based on `Cow` (https://github.com/google/xi-editor/pull/658)
- [x] select_next (https://github.com/google/xi-editor/issues/325) (https://github.com/google/xi-editor/pull/704)
    - [x] remove current selection and add next 
- [x] Plan replace RPC (https://github.com/google/xi-editor/issues/712)
- [x] Replace functionality (https://github.com/google/xi-editor/pull/720)
- [x] Search using multiple queries (https://github.com/google/xi-editor/pull/745)
- [x] Support colorizing of results based on groupings when using regular expressions and multiple queries (https://github.com/google/xi-editor/pull/745)
- [x] `Option` instead of custom `None` in enums (https://github.com/google/xi-editor/pull/741, #704)
- [x] Documentation and tests

Updating documentation and tests is part of each of these steps.
Other issues related to this: https://github.com/google/xi-editor/issues/224, https://github.com/google/xi-editor/issues/504
