### ISSUE TITLE
[GSoC] Language Server Protocol Plugin Support

### ISSUE THREAD

**Issue by betterclever** [google/xi-editor#659]
This is a roadmap of the the steps planned by me to add support for the Language Server Protocol (LSP) Plugin Support in the Xi Editor.

### Roadmap
_Will be refined over time_

- [ ] Get a basic plugin working which can access the document state.
- [ ] Discover improvements needed in current Plugin API to enable a very simple LSP usecase i.e. JSON.
- [ ] Get the JSON Plugin Working. The basic idea is to develop a crate which is abstraction over the plugin_lib, which JSON Plugin will use to communicate with the Editor. The validation error messages can be dumped to stderr to begin with.
- [ ] Figure out a plan for the features in a specific order in the LSP Plugin including:
    - [ ] Status Information
    - [ ] Inline Error and Warning Display 
    - [ ] Hover Definitions
    - [ ] Go to Definition
    - [ ] Intelligent Autocompletion
    - [ ] Highlight References
    - [ ] Refactoring Support
- [ ] Figure out a test language (probably Rust?) to begin with to implement and test all
features.

**TODO**: More refined steps after the 4th step.

### Planning

The basic architecture currently planned (needs review) can be described by the following picture.

![lsp-archtecture](https://user-images.githubusercontent.com/16309034/40114310-f57da422-58fb-11e8-9325-74c34ff2f5b5.png)

### Roadblocks / Open Questions.

- **Managing Workspaces**. Who should manage the workspaces: Xi-Core or the Plugin itself?

**Comment by skyne98** [comment]
@cmyr, hey, any progress? What is the state of LSP support in Xi? Thanks!

**Comment by jansol** [comment]
Many (most?) bits have PRs that at least were in a relatively working state. However they got kind of stuck in a discussion of how these things should be communicated to the client... The annotations PR (#1010) is one step towards specifying that.

**Comment by cmyr** [comment]
@skyne98 there was a bunch of exploratory work on this this summer, but the conclusion of that was that we should step back and work on incrementally adding support for the features that will _enable_ LSP support in the future. The issue linked above is a first step there.

**Comment by ShalokShalom** [comment]
@cmyr  And is there a list which we can follow about those spoken features?
