### ISSUE TITLE
Adopt rustfmt

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#673]
At some point we will want to start using rustfmt, and include a rustfmt pass in CI.

Todos:
- [ ] Update contributing.md to mention rustfmt (also clippy, which was added a while back)
- [ ] Add [`rustfmt.toml`](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md)
- [ ] Add rustfmt to [CI](https://github.com/rust-lang-nursery/rustfmt#checking-style-on-a-ci-server)
- [ ] Format all existing crates
- [ ] add some little `pre-merge.sh` script that runs rustfmt and clippy? (And mention this in contributing.md?)

Formatting options bikeshed:
In general I'm happy to just stick with the defaults. I would prefer [`fn_args_density`](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#fn_args_density) to be 'compressed', but that option isn't stable so can do without.

I don't love `max_width = 100`. I like aiming for 80, but making that a hard limit might be annoying?

If anyone wants to take a stab at this you're very welcome. 😎

**Comment by Lapz** [comment]
I'll work on this

**Comment by cmyr** [comment]
@Lapz cool, thanks!

**Comment by Lapz** [comment]
I been working on this and have decided to use a pre git commit hook for the pre-merge.sh script.Would that be ok?
I've also encountered a [bug](https://github.com/rust-lang-nursery/rustfmt/issues/2760) with rustfmt that I've reported upstream.

**Comment by cmyr** [comment]
@Lapz yea I think that pre-commit would make sense. Maybe adding that can be a separate PR? It can also include running clippy.

We do also have a `ci.local` script in the project root that is intended to run all the tests, it hasn't been used much though.
